### ISSUE TITLE
LWRP not speaking?

### ISSUE THREAD

**Issue by MrMMorris** [cwjohnston/chef-hipchat#15]
I am using the LWRP like this:

``` ruby
hipchat_msg 'deployment' do
  room 'CI'
  token node['hipchat-token']
  message "Successful deployment of #{node['web']['revision']} branch on #{node['app']['name']}-#{node.chef_environment}"
  color 'green'
end
```

but in the run I only get `hipchat_msg[deployment] action speak (up to date)` and nothing appears in the room. Do I have to notify from another resource?

**Comment by MrMMorris** [comment]
nope, just using the really old version on the Supermarket. +1 for a release https://github.com/cwjohnston/chef-hipchat/issues/7

**Comment by MrMMorris** [comment]
Maybe not. I get `hipchat_msg[deployment] action speak` now, but still nothing in the room. Is this related to API v2?

**Comment by MrMMorris** [comment]
looks like I get `HipChat::Unauthorized: Access denied to room 'Alerts'` for the handler as well. I will wait patiently for v2 API integration :shipit:

**Comment by cwjohnston** [comment]
@MrMMorris I think your most recent issue is resolved by the changes I've just released in 0.4.0, assuming you appropriately adjust the handler attributes to specify api v2. I'm going to close this issue but please feel free to reopen it if you find that your problem is not addressed.

**Comment by MrMMorris** [comment]
@cwjohnston good news and bad news. 

Good: I ran chef with debug and realized that the LWRP didn't work because I didn't specify the nickname. Not sure if you want to throw an error for that or not.

The bad news: The handler still isn't working. 

Here are the attributes for the handler:

``` ruby
force_default['hipchat']['handler']['room'] = 'Alerts'
force_default['hipchat']['handler']['enabled'] = true
force_default['hipchat']['handler']['api_version'] = 'v2'
force_default['hipchat']['handler']['token'] = <correct_token>
```

And here is the stack trace from the error:

```
[2014-10-07T00:25:42+00:00] ERROR: Report handler HipChat::NotifyRoom raised #<HipChat::Unauthorized: Access denied to room `Alerts'>
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/hipchat-1.2.0/lib/hipchat/room.rb:108:in `send'
[2014-10-07T00:25:42+00:00] ERROR: /var/chef/handlers/hipchat.rb:54:in `report'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:226:in `run_report_unsafe'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:214:in `run_report_safely'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:117:in `each'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:117:in `run_exception_handlers'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:133:in `call'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:133:in `block in run_failed'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:132:in `each'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:132:in `run_failed'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:447:in `rescue in do_run'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:459:in `do_run'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:213:in `block in run'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:207:in `fork'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/client.rb:207:in `run'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application.rb:236:in `run_chef_client'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:338:in `block in run_application'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:327:in `loop'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application/client.rb:327:in `run_application'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/application.rb:55:in `run'
[2014-10-07T00:25:42+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/bin/chef-client:26:in `<top (required)>'
[2014-10-07T00:25:42+00:00] ERROR: /usr/bin/chef-client:23:in `load'
[2014-10-07T00:25:42+00:00] ERROR: /usr/bin/chef-client:23:in `<main>'
    - HipChat::NotifyRoom
```

I even get `Access denied` when I provide a room that _doesn't exist_ which is weird. I have also tried using both 'Notification' and 'Admin' API tokens.

Thanks so much for the release. I'm eager to get it all working as we go live tomorrow!

**Comment by cwjohnston** [comment]
@MrMMorris AFAIK 'admin' and 'notification' tokens are specific to the 'v1' API and won't work with the 'v2' API. Can you please try again with api_version = 'v1' or use a 'v2' compatible token (see https://www.hipchat.com/docs/apiv2/auth)?

**Comment by MrMMorris** [comment]
@cwjohnston I was able to get the handler working using a room token. However, it seems that the same does not work for the LWRP. I can only get the LWRP to work with a API v1 token. Not sure if that's expected.

Either way, I have something that works!

**Comment by MrMMorris** [comment]
Now I can't get the handler to work with a v2 room token. I'm pretty sure it was working yesterday, but now I get: 

`HipChat::NotifyRoom raised #<HipChat::UnknownResponseCode: Unexpected 400 for room 'Alerts'>`

I have since reverted to using a v1 token for both the handler and the LWRP.
